/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Square721_BT14.c                                      *
* Font:        Square721 BT                                          *
* Height:      14                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  14                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x41 (65)                                     *
* Character enabled:   0x76 (118)                                    *
* Character enabled:   0x65 (101)                                    *
* Character enabled:   0x72 (114)                                    *
* Character enabled:   0x61 (97)                                     *
* Character enabled:   0x67 (103)                                    *
* Character enabled:   0x52 (82)                                     *
* Character enabled:   0x6E (110)                                    *
* Character enabled:   0x4B (75)                                     *
* Character enabled:   0x4D (77)                                     *
* Character enabled:   0x57 (87)                                     *
* Character enabled:   0x2F (47)                                     *
* Character disabled:  0x4D (77)                                     *
* Character disabled:  0x4B (75)                                     *
* Character disabled:  0x57 (87)                                     *
* Character disabled:  0x2F (47)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSquare721_BT14;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT14_0041[ 52] = { /* code 0041, LATIN CAPITAL LETTER A */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x3D, 0xA1, 0x00,
  0x01, 0x77, 0xA3, 0x00,
  0x02, 0xA3, 0x77, 0x10,
  0x04, 0x91, 0x3A, 0x10,
  0x18, 0x50, 0x19, 0x40,
  0x2D, 0xFF, 0xFF, 0x91,
  0x69, 0x10, 0x02, 0xB2,
  0xA4, 0x00, 0x01, 0x96,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT14_0052[ 52] = { /* code 0052, LATIN CAPITAL LETTER R */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x3E, 0xFF, 0xFE, 0x71,
  0x3A, 0x20, 0x15, 0xC2,
  0x3A, 0x20, 0x02, 0xB2,
  0x3A, 0x20, 0x15, 0xB2,
  0x3E, 0xFF, 0xFF, 0x71,
  0x3A, 0x20, 0x15, 0xB2,
  0x3A, 0x20, 0x02, 0xB2,
  0x3A, 0x20, 0x02, 0xB2,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT14_0061[ 39] = { /* code 0061, LATIN SMALL LETTER A */
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x2C, 0xFF, 0xD4,
  0x00, 0x01, 0x86,
  0x3C, 0xFE, 0xC7,
  0x69, 0x11, 0x97,
  0x6A, 0x11, 0x97,
  0x3C, 0xFE, 0xB7,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT14_0065[ 39] = { /* code 0065, LATIN SMALL LETTER E */
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x2B, 0xFF, 0xC4,
  0x5A, 0x11, 0x78,
  0x6F, 0xFF, 0xF9,
  0x68, 0x10, 0x00,
  0x5A, 0x11, 0x88,
  0x1A, 0xFF, 0xC3,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT14_0067[ 39] = { /* code 0067, LATIN SMALL LETTER G */
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x19, 0xFE, 0xA9,
  0x3B, 0x22, 0x99,
  0x49, 0x10, 0x59,
  0x49, 0x10, 0x59,
  0x3B, 0x22, 0x99,
  0x19, 0xFE, 0xA9,
  0x00, 0x01, 0x58,
  0x2B, 0xFF, 0xC3
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT14_006E[ 39] = { /* code 006E, LATIN SMALL LETTER N */
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x4B, 0xCF, 0xC3,
  0x4D, 0x41, 0x87,
  0x4A, 0x10, 0x58,
  0x49, 0x10, 0x58,
  0x49, 0x10, 0x58,
  0x49, 0x10, 0x58,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT14_0072[ 39] = { /* code 0072, LATIN SMALL LETTER R */
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x4B, 0xCF, 0x70,
  0x4C, 0x34, 0xB0,
  0x4A, 0x11, 0x40,
  0x4A, 0x10, 0x00,
  0x4A, 0x10, 0x00,
  0x4A, 0x10, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT14_0076[ 39] = { /* code 0076, LATIN SMALL LETTER V */
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0xA3, 0x02, 0xA0,
  0x76, 0x14, 0x90,
  0x39, 0x18, 0x50,
  0x1A, 0x4A, 0x20,
  0x17, 0xA9, 0x10,
  0x03, 0xE5, 0x00,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSquare721_BT14_CharInfo[8] = {
   {   8,   8,  4, acGUI_FontSquare721_BT14_0041 } /* code 0041 */
  ,{   8,   8,  4, acGUI_FontSquare721_BT14_0052 } /* code 0052 */
  ,{   6,   6,  3, acGUI_FontSquare721_BT14_0061 } /* code 0061 */
  ,{   6,   6,  3, acGUI_FontSquare721_BT14_0065 } /* code 0065 */
  ,{   6,   6,  3, acGUI_FontSquare721_BT14_0067 } /* code 0067 */
  ,{   6,   6,  3, acGUI_FontSquare721_BT14_006E } /* code 006E */
  ,{   5,   5,  3, acGUI_FontSquare721_BT14_0072 } /* code 0072 */
  ,{   5,   5,  3, acGUI_FontSquare721_BT14_0076 } /* code 0076 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT14_Prop8 = {
   0x0076 /* first character */
  ,0x0076 /* last character  */
  ,&GUI_FontSquare721_BT14_CharInfo[  7] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT14_Prop7 = {
   0x0072 /* first character */
  ,0x0072 /* last character  */
  ,&GUI_FontSquare721_BT14_CharInfo[  6] /* address of first character */
  ,&GUI_FontSquare721_BT14_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT14_Prop6 = {
   0x006E /* first character */
  ,0x006E /* last character  */
  ,&GUI_FontSquare721_BT14_CharInfo[  5] /* address of first character */
  ,&GUI_FontSquare721_BT14_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT14_Prop5 = {
   0x0067 /* first character */
  ,0x0067 /* last character  */
  ,&GUI_FontSquare721_BT14_CharInfo[  4] /* address of first character */
  ,&GUI_FontSquare721_BT14_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT14_Prop4 = {
   0x0065 /* first character */
  ,0x0065 /* last character  */
  ,&GUI_FontSquare721_BT14_CharInfo[  3] /* address of first character */
  ,&GUI_FontSquare721_BT14_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT14_Prop3 = {
   0x0061 /* first character */
  ,0x0061 /* last character  */
  ,&GUI_FontSquare721_BT14_CharInfo[  2] /* address of first character */
  ,&GUI_FontSquare721_BT14_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT14_Prop2 = {
   0x0052 /* first character */
  ,0x0052 /* last character  */
  ,&GUI_FontSquare721_BT14_CharInfo[  1] /* address of first character */
  ,&GUI_FontSquare721_BT14_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT14_Prop1 = {
   0x0041 /* first character */
  ,0x0041 /* last character  */
  ,&GUI_FontSquare721_BT14_CharInfo[  0] /* address of first character */
  ,&GUI_FontSquare721_BT14_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSquare721_BT14 = {
   GUI_FONTTYPE_PROP_AA4 /* type of font    */
  ,14 /* height of font  */
  ,14 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSquare721_BT14_Prop1}
  ,11 /* Baseline */
  ,6 /* Height of lowercase characters */
  ,8 /* Height of capital characters */
};

