/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Square721_BT10.c                                      *
* Font:        Square721 BT                                          *
* Height:      10                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  10                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x4D (77)                                     *
* Character enabled:   0x2F (47)                                     *
* Character enabled:   0x4B (75)                                     *
* Character enabled:   0x57 (87)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSquare721_BT10;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT10_002F[ 10] = { /* code 002F, SOLIDUS */
  0x00,
  0x00,
  0x05,
  0x17,
  0x27,
  0x45,
  0x63,
  0x71,
  0x61,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT10_004B[ 30] = { /* code 004B, LATIN CAPITAL LETTER K */
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x55, 0x15, 0x80,
  0x55, 0x48, 0x10,
  0x5B, 0x91, 0x00,
  0x58, 0x93, 0x00,
  0x55, 0x29, 0x30,
  0x55, 0x03, 0x90,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT10_004D[ 40] = { /* code 004D, LATIN CAPITAL LETTER M */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x5C, 0x20, 0x17, 0xB1,
  0x5A, 0x50, 0x19, 0x91,
  0x57, 0x81, 0x47, 0x81,
  0x56, 0x73, 0x74, 0x81,
  0x55, 0x48, 0x82, 0x81,
  0x55, 0x1B, 0x62, 0x81,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT10_0057[ 40] = { /* code 0057, LATIN CAPITAL LETTER W */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x83, 0x19, 0x91, 0x28,
  0x65, 0x19, 0x92, 0x46,
  0x37, 0x38, 0x74, 0x74,
  0x28, 0x65, 0x46, 0x82,
  0x18, 0xA3, 0x2A, 0x81,
  0x06, 0xB1, 0x1A, 0x61,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSquare721_BT10_CharInfo[4] = {
   {   2,   2,  1, acGUI_FontSquare721_BT10_002F } /* code 002F */
  ,{   5,   5,  3, acGUI_FontSquare721_BT10_004B } /* code 004B */
  ,{   8,   8,  4, acGUI_FontSquare721_BT10_004D } /* code 004D */
  ,{   8,   8,  4, acGUI_FontSquare721_BT10_0057 } /* code 0057 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT10_Prop4 = {
   0x0057 /* first character */
  ,0x0057 /* last character  */
  ,&GUI_FontSquare721_BT10_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT10_Prop3 = {
   0x004D /* first character */
  ,0x004D /* last character  */
  ,&GUI_FontSquare721_BT10_CharInfo[  2] /* address of first character */
  ,&GUI_FontSquare721_BT10_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT10_Prop2 = {
   0x004B /* first character */
  ,0x004B /* last character  */
  ,&GUI_FontSquare721_BT10_CharInfo[  1] /* address of first character */
  ,&GUI_FontSquare721_BT10_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT10_Prop1 = {
   0x002F /* first character */
  ,0x002F /* last character  */
  ,&GUI_FontSquare721_BT10_CharInfo[  0] /* address of first character */
  ,&GUI_FontSquare721_BT10_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSquare721_BT10 = {
   GUI_FONTTYPE_PROP_AA4 /* type of font    */
  ,10 /* height of font  */
  ,10 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSquare721_BT10_Prop1}
  ,8 /* Baseline */
  ,4 /* Height of lowercase characters */
  ,6 /* Height of capital characters */
};

