/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Square721_BT10.c                                      *
* Font:        Square721 BT                                          *
* Height:      10                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  10                                           *
* Range disabled:       0000 - FFFF                                  *
* Character enabled:   0x4B (75)                                     *
* Character enabled:   0x4D (77)                                     *
* Character enabled:   0x2F (47)                                     *
* Character enabled:   0x57 (87)                                     *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontSquare721_BT10;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT10_002F[ 10] = { /* code 002F, SOLIDUS */
  0x00,
  0x00,
  0x06,
  0x18,
  0x29,
  0x47,
  0x74,
  0x92,
  0x81,
  0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT10_004B[ 30] = { /* code 004B, LATIN CAPITAL LETTER K */
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00,
  0x7E, 0x4A, 0xE4,
  0x7E, 0x8F, 0x81,
  0x7F, 0xFC, 0x20,
  0x7F, 0xED, 0x30,
  0x7E, 0x7E, 0xA1,
  0x7E, 0x48, 0xF6,
  0x00, 0x00, 0x00,
  0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT10_004D[ 40] = { /* code 004D, LATIN CAPITAL LETTER M */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0x7F, 0xE3, 0x2C, 0xF8,
  0x7F, 0xF5, 0x4E, 0xF8,
  0x7E, 0xD9, 0x7D, 0xE8,
  0x7E, 0x9C, 0xCA, 0xE8,
  0x7E, 0x6E, 0xF6, 0xD8,
  0x7E, 0x4C, 0xD4, 0xD8,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE unsigned char acGUI_FontSquare721_BT10_0057[ 40] = { /* code 0057, LATIN CAPITAL LETTER W */
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00,
  0xAD, 0x3C, 0xE4, 0x9D,
  0x8E, 0x4E, 0xF6, 0xBC,
  0x6E, 0x7E, 0xD9, 0xCA,
  0x4E, 0xBC, 0xAC, 0xE8,
  0x3E, 0xFA, 0x7F, 0xF6,
  0x2D, 0xF8, 0x5F, 0xE4,
  0x00, 0x00, 0x00, 0x00,
  0x00, 0x00, 0x00, 0x00
};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontSquare721_BT10_CharInfo[4] = {
   {   2,   2,  1, acGUI_FontSquare721_BT10_002F } /* code 002F */
  ,{   6,   6,  3, acGUI_FontSquare721_BT10_004B } /* code 004B */
  ,{   8,   8,  4, acGUI_FontSquare721_BT10_004D } /* code 004D */
  ,{   8,   8,  4, acGUI_FontSquare721_BT10_0057 } /* code 0057 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT10_Prop4 = {
   0x0057 /* first character */
  ,0x0057 /* last character  */
  ,&GUI_FontSquare721_BT10_CharInfo[  3] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT10_Prop3 = {
   0x004D /* first character */
  ,0x004D /* last character  */
  ,&GUI_FontSquare721_BT10_CharInfo[  2] /* address of first character */
  ,&GUI_FontSquare721_BT10_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT10_Prop2 = {
   0x004B /* first character */
  ,0x004B /* last character  */
  ,&GUI_FontSquare721_BT10_CharInfo[  1] /* address of first character */
  ,&GUI_FontSquare721_BT10_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontSquare721_BT10_Prop1 = {
   0x002F /* first character */
  ,0x002F /* last character  */
  ,&GUI_FontSquare721_BT10_CharInfo[  0] /* address of first character */
  ,&GUI_FontSquare721_BT10_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontSquare721_BT10 = {
   GUI_FONTTYPE_PROP_AA4 /* type of font    */
  ,10 /* height of font  */
  ,10 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontSquare721_BT10_Prop1}
  ,8 /* Baseline */
  ,4 /* Height of lowercase characters */
  ,6 /* Height of capital characters */
};

